# Use an official Python runtime as a parent image
FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements/requirements_extract_features.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_extract_features.txt

COPY scripts/extract_features.py /root
COPY scripts/crop_image.py /root

VOLUME /root/.keras
VOLUME /data

WORKDIR /root

ENTRYPOINT ["python3", "extract_features.py"]
