# docker run --rm -it $(pwd)/../videos:/video:ro -v $(pwd)/static/features_videos:/data -v /home/.keras/:/root/.keras $(pwd)/../videos:/video:ro jacobloe/extract_features:0.1 /data/ /video/file_mappings.tsv

# Use an official Python runtime as a parent image
FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_extract_features.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_extract_features.txt

COPY extract_features.py /root
COPY crop_image.py /root
COPY idmapper.py /root

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "extract_features.py"]
