#docker run --rm -it -v $(pwd)/static/features_videos:/root/static -p 5000:80 jacobloe/flask_query:0.1

#docker build -f Dockerfile_flask_query -t jacobloe/flask_query:0.1 .

# Use an official Python runtime as a parent image
FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_flask_query.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_flask_query.txt

COPY flask_query.py /root
COPY query.py /root
COPY extract_features.py /root

#COPY keras.json /root/.keras
#COPY inception_resnet_v2_weights_tf_dim_ordering_tf_kernels_notop.h5 /root/.keras/models

EXPOSE 80

VOLUME "/data"

ENV NAME World

WORKDIR /root

CMD ["python3", "flask_query.py"]
