FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_server_setup.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_server_setup.txt

COPY server_setup.py /root
COPY query.py /root
COPY extract_features.py /root

EXPOSE 9000

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "server_setup.py"]
