#docker run --rm -it -v $(pwd)/static/features_videos:/data  jacobloe/extract_features:0.1 /data/

#docker build -f Dockerfile_extract_features -t jacobloe/extract_features:0.1 .

# Use an official Python runtime as a parent image
FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_extract_features.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_extract_features.txt

COPY extract_features.py /root

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "extract_features.py"]
