# Use an official Python runtime as a parent image
FROM python:3.6.8-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y shotdetect=1.0.86-5+b1 && apt-get clean && rm -rf /var/lib/apt/lists

RUN pip3 install --trusted-host pypi.python.org argparse==1.4.0
RUN pip3 install tqdm==4.43.0

COPY ndd/shotdetect.py /root

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "shotdetect.py"]
