# opencv needs the python-stretch version
FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements/requirements_extract_images.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_extract_images.txt
RUN apt update && apt install -y ffmpeg

COPY ndd/extract_images.py /root
COPY ndd/utils.py /root

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "extract_images.py"]
