#docker run --rm -it -v $(pwd)/../videos:/video:ro -v $(pwd)/static/features_videos:/data  jacobloe/extract_images:0.1 /video /data/

#docker build -f Dockerfile_extract_images -t jacobloe/extract_images:0.1 .

# opencv needs the python-stretch version
FROM python:3.6.8-stretch 

ENV DEBIAN_FRONTEND noninteractive

COPY extract_images.py /root
COPY requirements_extract_images.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_extract_images.txt

VOLUME "/video"
VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "extract_images.py"]
