FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements/requirements_server_ndd.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_server_ndd.txt

COPY ndd/server_ndd.py /root
COPY ndd/extract_features.py /root
COPY ndd/utils.py /root

EXPOSE 9000

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "server_ndd.py"]
