FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_client_ndd.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_client_ndd.txt

COPY client_ndd.py /root

EXPOSE 9000

WORKDIR /root

CMD ["python3", "client_ndd.py"]
