#docker run --rm -it -v $(pwd)/static/features_videos:/data  -p 5000:80 jacobloe/flask_query:0.1

#docker build -f dockerfile_flask_query -t jacobloe/flask_query:0.1 .

# Use an official Python runtime as a parent image
FROM python:3.6.8-stretch

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /root

COPY flask_query.py /root
COPY query.py /root
COPY extract_features.py /root
COPY requirements_flask_query.txt /root

RUN pip3 install --trusted-host pypi.python.org -r requirements_flask_query.txt

EXPOSE 80

VOLUME "/data"

ENV NAME World

CMD ["python3", "flask_query.py"]
